plugins {
    id 'com.android.application'
}

android {
    namespace 'com.soui.cnchess'
    compileSdk 34

    defaultConfig {
        applicationId "com.soui.cnchess"
        minSdk 28
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
        externalNativeBuild {
            cmake {
                //编译说明：由于需要链接soui-android-lib编译出来的so，直接从soui-android-lib的build/intermediates/library_jni的时机好像不对。
                //现在我的方法是先编译soui-android-lib模块，再手动将soui-android-lib/build/intermediates/library_jni复制到soui-android-lib的build/library_jni
                //经过这样处理就可以正常链接到soui的so了。
                //启程软件 2026-8-4
                cppFlags "-std=c++17 -fexceptions -frtti"
                arguments "-DANDROID_STL=c++_shared",
                        "-DSOUI_INCLUDE_DIR=${project(':soui-android-lib').projectDir.absolutePath.replace('\\', '/')}/src/main/assets/soui4",
                        "-DSOUI4ANDROID_INCLUDE_DIR=${project(':soui-android-lib').projectDir.absolutePath.replace('\\', '/')}/src/main/cpp/include",
                        "-DSOUI_LIB_DIR=${project(':soui-android-lib').buildDir.absolutePath.replace('\\', '/')}/library_jni/debug/jni",
                        "-DSOUI_CONTROLS_EXTEND_DIR=${rootDir.absolutePath.replace('\\', '/')}/../../../../controls.extend",
                        "-DCNCHESS_CLIENT_DIR=${rootDir.absolutePath.replace('\\', '/')}/..",
                        "-DCNCHESS_ROOT_DIR=${rootDir.absolutePath.replace('\\', '/')}/../.."
            }
        }
        ndk {
            abiFilters 'x86', 'arm64-v8a', 'x86_64', 'armeabi-v7a'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug

        }
    }

    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.18.1"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    // 引用 soui-android-lib 模块
    implementation project(':soui-android-lib')

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
